---
version: 1

name: web-community-cdn

pipelines:
  prd:
    phases:
      - type: github
        name: GitHub
        owner: byu-oit
        repo: web-cdn
        branch: master
      - type: codebuild
        name: Build
        build_image: aws/codebuild/standard:3.0
        environment_variables:
          ENV: prd
          ROOT_DNS: cdn.byu.edu
          CONFIG_BRANCH: master
          CERTIFICATE_ARN: arn:aws:acm:us-east-1:204581410681:certificate/18c1b547-de51-43d3-afa5-2bd05493c41c
        build_role: web-community-cdn-cfn-deploy
        cache: s3
      - type: slack_notify
        name: Notify
        message: "Prd CDN Assembler Build Finished (cdn.byu.edu)"
        channel: "#custom-code-bots"
  dev:
    phases:
      - type: github
        name: GitHub
        owner: byu-oit
        repo: web-cdn
        branch: dev
      - type: codebuild
        name: Build
        build_image: aws/codebuild/standard:3.0
        environment_variables:
          ENV: dev
          ROOT_DNS: cdn-dev.byu.edu
          CONFIG_BRANCH: dev
          CERTIFICATE_ARN: arn:aws:acm:us-east-1:632558792265:certificate/1bc2f81c-2f79-46b3-9d3b-54ce672ba8be
        build_role: web-community-cdn-cfn-deploy
        cache: s3
      - type: slack_notify
        name: Notify
        message: "Dev CDN Assembler Build Finished (cdn-dev.byu.edu)"
        channel: "#custom-code-bots"

